### ISSUE TITLE
problem of downloading the database

### ISSUE THREAD

**Issue by yuxiangtan** [SegataLab/PanPhlAn_pangenome_exporter#4] opened 2022-04-10 15:09 UTC
Dear authors,

I tried the download_databases.py, it failed.
And I tried to directly download the link from it and it returned 404 error. (Attached figures)

![361adc6a79c5bd25b459b7e861f5ab2](https://user-images.githubusercontent.com/10011271/162625987-a7dc4828-8e1e-49bc-8a95-60a0767daae0.png)
![729295b1bfc85a442709c3bb0e8d2c2](https://user-images.githubusercontent.com/10011271/162625995-46a81bf1-7c31-4309-a492-dd8f390249ba.png)

Without the database files, how can I generate database by myself? I found in Humann3 there are similar diamond indexes, but UniRef90to50_201906.tsv.bz2 was not found anywhere.

Best,

Yuxiang

**Comment by leonarDubois** [comment] 2022-04-11 13:27
Hi, 

indeed the files were removed due to some Dropbox account being closed recently. We will upload them again and update the URL in the code. I'll let you know when the problem is solved.

Have a nice day

**Comment by leonarDubois** [comment] 2022-04-12 08:21
Hi, should be fixed. Let me know if something's still wrong

**Closed as completed** 2022-04-19 08:24 UTC
